import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col justify-between`}>
        <header className="w-full bg-blue-600 text-white py-6 text-center">
          <h1 className="text-4xl font-bold">Car Dealer</h1>
        </header>

        <main className="w-full W-[40vW] flex justify-center items-center p-4">
          {children}
        </main>

        <footer className="w-full bg-gray-800 text-white py-4 text-center mt-auto">
          <p>Built by Helena Maia ♥</p>
        </footer>
      </body>
    </html>
  );
}
